# Generated by Django 5.2.17 on 2026-08-25 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('contenido', models.TextField()),
                ('tipo', models.CharField(choices=[('spec', 'Especificación'), ('design', 'Diseño'), ('api', 'Documentación API'), ('user_guide', 'Guía de Usuario'), ('changelog', 'Registro de Cambios'), ('meeting', 'Acta de Reunión'), ('report', 'Reporte'), ('other', 'Otro')], default='other', max_length=20)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('tags', models.JSONField(default=list)),
                ('metadata', models.JSONField(default=dict)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='BusquedaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=500)),
                ('resultados_encontrados', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('documento_seleccionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doc_memory.documento')),
            ],
            options={
                'verbose_name_plural': 'Búsquedas de documentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemoriaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=255)),
                ('valor', models.TextField()),
                ('contexto', models.TextField(blank=True)),
                ('relevancia', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memorias', to='doc_memory.documento')),
            ],
            options={
                'ordering': ['-relevancia', '-updated_at'],
                'unique_together': {('documento', 'clave')},
            },
        ),
        migrations.CreateModel(
            name='ReferenciaCruzada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_relacion', models.CharField(default='referencia', max_length=50)),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('documento_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referencias_entrada', to='doc_memory.documento')),
                ('documento_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referencias_salida', to='doc_memory.documento')),
            ],
            options={
                'unique_together': {('documento_origen', 'documento_destino')},
            },
        ),
    ]
