# Generated by Django 5.2.17 on 2026-08-25 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_queries', models.IntegerField(default=0)),
                ('slow_queries', models.IntegerField(default=0)),
                ('avg_query_time', models.FloatField(default=0)),
                ('total_rows_scanned', models.BigIntegerField(default=0)),
                ('cache_hit_ratio', models.FloatField(default=0)),
                ('recommendations_applied', models.IntegerField(default=0)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='IndexRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=255)),
                ('index_name', models.CharField(max_length=255)),
                ('columns', models.JSONField()),
                ('index_type', models.CharField(default='btree', max_length=50)),
                ('priority', models.CharField(choices=[('high', 'Alta'), ('medium', 'Media'), ('low', 'Baja')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('applied', 'Aplicada'), ('rejected', 'Rechazada')], default='pending', max_length=10)),
                ('reason', models.TextField()),
                ('estimated_improvement', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TableStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=255, unique=True)),
                ('row_count', models.BigIntegerField(default=0)),
                ('table_size_mb', models.FloatField(default=0)),
                ('index_size_mb', models.FloatField(default=0)),
                ('sequential_scans', models.IntegerField(default=0)),
                ('index_scans', models.IntegerField(default=0)),
                ('last_vacuum', models.DateTimeField(blank=True, null=True)),
                ('last_analyze', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('query_sql', models.TextField()),
                ('duration_ms', models.FloatField()),
                ('tables_involved', models.JSONField(default=list)),
                ('is_slow', models.BooleanField(default=False)),
                ('suggested_indexes', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
