# Generated by Django 5.2.17 on 2026-08-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EndpointDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], max_length=10)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('categoria', models.CharField(default='general', max_length=100)),
                ('parametros', models.JSONField(default=list)),
                ('body_schema', models.JSONField(default=dict)),
                ('response_schema', models.JSONField(default=dict)),
                ('ejemplos', models.JSONField(default=list)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['path', 'method'],
                'unique_together': {('path', 'method')},
            },
        ),
    ]
